{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "tf.set_random_seed(1)\n",
    "np.random.seed(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "x = np.linspace(-1, 1, 100)[:, np.newaxis]\n",
    "noise = np.random.normal(0, 0.1, size=x.shape)\n",
    "y = np.power(x, 2) + noise"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def save():\n",
    "    tf_x = tf.placeholder(tf.float32, x.shape)\n",
    "    tf_y = tf.placeholder(tf.float32, y.shape)\n",
    "    l = tf.layers.dense(tf_x, 10, tf.nn.relu)\n",
    "    o = tf.layers.dense(l, 1)\n",
    "    loss = tf.losses.mean_squared_error(tf_y, o)\n",
    "    train_op = tf.train.GradientDescentOptimizer(learning_rate=0.5).minimize(loss)\n",
    "    with tf.Session() as sess:\n",
    "        sess.run(tf.global_variables_initializer())\n",
    "        saver = tf.train.Saver()\n",
    "        for step in range(100):\n",
    "            sess.run(train_op, {tf_x: x, tf_y: y})\n",
    "        saver.save(sess, \"./params\", write_meta_graph=False)\n",
    "        \n",
    "        pred, l = sess.run([o, loss], {tf_x: x, tf_y: y})\n",
    "        plt.scatter(x, y)\n",
    "        plt.plot(x, pred, \"r-\", lw=5)\n",
    "        plt.text(-1, 1.2, \"Save Loss=%.4f\" % l)\n",
    "        plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def reload():\n",
    "    tf_x = tf.placeholder(tf.float32, x.shape)\n",
    "    tf_y = tf.placeholder(tf.float32, y.shape)\n",
    "    l_ = tf.layers.dense(tf_x, 10, tf.nn.relu)\n",
    "    o_ = tf.layers.dense(l_, 1)\n",
    "    loss_ = tf.losses.mean_squared_error(tf_y, o_)\n",
    "    with tf.Session() as sess:\n",
    "        saver = tf.train.Saver()\n",
    "        saver.restore(sess, \"./params\")\n",
    "        \n",
    "        pred, l = sess.run([o_, loss_], {tf_x: x, tf_y: y})\n",
    "        plt.scatter(x, y)\n",
    "        plt.plot(x, pred, \"r-\", lw=5)\n",
    "        plt.text(-1, 1.2, \"Reload Loss=%.4f\" % l, fontdict={\"size\": 15, \"color\": \"red\"})\n",
    "        plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXYAAAD6CAYAAAC1W2xyAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz\nAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMS4yLCBo\ndHRwOi8vbWF0cGxvdGxpYi5vcmcvNQv5yAAAIABJREFUeJzt3Xd4VFX6wPHvSQgYQgklIESaSm8q\nKCItIE0QRKTYcG0L62JDRUBYQZfmothxpaj7EwuoEJEiRTorrkEpS1sEAxqqkBACCYTk/P64GUjm\n3kmm3JnMTN7P8/CQ3HPmzpvJzTtnzj1Faa0RQggRPiKKOwAhhBD2ksQuhBBhRhK7EEKEGUnsQggR\nZiSxCyFEmJHELoQQYUYSuxBChBlJ7EIIEWYksQshRJgpVRxPWrVqVV23bl2vH5+Tk0NycjIXL16k\ndOnS1K1bF6WUfQEChw8fpkyZMlSpUsXW8zpLTk4mKyuLihUrUqNGDY/qZWdnc+DAARo2bAiA1pr9\n+/dz8eJFqlatStWqVS89PjMzk99++40GDRr49ecRQvjPli1b/tBaxxVVr1gSe926dUlKSvL68f/8\n5z9JT0/n+eef59FHH2XYsGHceOONNkYIEyZM4Nprr+X++++35XzDhg1j7969l77v0qULzZo1Y9Gi\nRXz00Uc8/PDDjBkzhvr165seu2DBAlO9qlWrcs899xAZGXnptZw+fTrp6elMmDCBXr16MW/ePMqX\nL4/Wmh49ehAXF8fatWtt+XmEEIGnlDroTr2Q7IqJj49n4cKF7Nu3j9mzZ3PjjTeSkZFBz5496dCh\nAw899BAAkyZNIjExEYApU6bwxRdfcO7cOQYMGEDHjh0ZPny4R897/vx57rnnHjp16sR9993HhQsX\nyMzM5Pbbb6djx47ceeedXLx40fLY+++/z9q1ay/9e/HFF1m7di2DBg0CoHv37mzcuNHyea3qRUZG\nMm/ePCpUqGBZr2PHjpcS/ocffkjnzp09+lmFEKHLrcSulKqulNpQSHltpdRapdRqpdRMZXe/iJM+\nffowYsQI+vfvz5NPPklOTg5HjhzhiSeeYNWqVSQnJ3Ps2DEGDhzIsmXLAFi/fj29evVi5syZNGvW\njPXr13PkyBG2b9/u9vPOmjWLZs2asW7dOurXr88HH3zArl27iIiIYP369Tz00ENkZGRYHrNy9uxZ\n4uPjAahcuTLHjh1zu16FChWoWLFikfVOnjzJ3Llzee6559z+OYUQoa3IxK6UqgT8C4gppNow4DGt\ndRegFtDcnvCs7du3j549e7J161ZOnDjB3LlziYqKYvbs2dx3332cOnWKzMxMGjRowO+//056ejqx\nsbHExMSwd+9eFi5cSEJCAgcOHCAlJcXt5921axdt2rQB4Oabb2b37t3ccMMNNGvWjO7du7N8+XLK\nli1reWzYsGEkJCRc+vfyyy9Trlw5MjMzAcjIyCA3N9fyeX2pN3r0aKZMmUJUVJTbP6cQIrS502LP\nAQYD6a4qaK3Haq13531bBfjDhthcmj17NgsXLiQyMpJmzZqRlZXFnDlzGDBgAJ999hkxMZffg266\n6SbeeOMN+vbtC0DDhg15+umnWbt2LRMnTqR27dpuP2/Tpk3ZvHkzAJs3b6Zp06Zs27aNdu3asWLF\nClJTU9mwYYPlMauumFatWl3qftm2bRuubij7Um/dunWMGjWKhIQEtm7dyrhx49z+eYUQIUpr7dY/\nYK0bdQYDH7ooGwokAUm1a9fWvkhJSdEJCQm6U6dOum/fvvrs2bN63bp1umnTprp9+/a6bdu2euPG\njVprrXfu3KkrVaqk09PTtdZaZ2Rk6IEDB+oOHTro3r1769OnT1s+x/jx43W9evV0q1atdKtWrfTb\nb7+ts7Ky9N133607dOig7733Xn3+/Hmdmpqqu3fvrtu2bas7d+6s09LSLI9ZOX36tG7RooUeMWKE\nbtSokU5LS9M7d+7UY8eOLbKeQ6dOnS59nZycrJs0aaKffPJJ3bp1a33x4sUC58lfVwgReoAk7Ua+\nVtrNjTaUUmu11gmFlF8NzAO6aq1PF3au1q1ba19GxYST1NRUVq5cSceOHbnyyit9rnf48GE2btxI\njx49TH3wQojQppTaorVuXWQ9OxJ7Xj/8t8CjWusdRZ1LErsQQnjO3cTu8Th2pVQXoInW+p18h0cD\ntYG38wbEjNdar/P03EVJ/DmFacv3cjgtk5qx0Yzs0ZB+18fb/TRCCBHS3G6x28mbFnvizymMWbCD\nzOycS8eioyKZ0r+5JHchRIngbos9ZCYoTVu+t0BSB8jMzmHa8r0uHiGEECVTyCT2w2mZHh0XQoiS\nKmQSe83YaI+OCyFESRUyiX1kj4ZER0UWOBYdFcnIHg2LKSIhhAhOxbK6ozccN0hlVIwQQhQuZBI7\nGMldErkQQhQuZLpihBBCuEcSuxBChBlJ7EIIEWYksQshRJiRxC6EEGFGErsQQoSZkBruKIQQoSjQ\nK9NKYhdCCD9yXpk2JS2TMQuMbSv8ldylK0YIIfyoOFamlcQuhBB+VBwr00piF0IIPyqOlWklsQsh\nhB8Vx8q0cvNUCCH8qDhWppXELoQQfhbolWmlK0YIIcKMJHYhhAgzktiFECLMuJXYlVLVlVIbCimP\nUkp9o5TapJR62L7whBBCeKrIxK6UqgT8C4gppNoTwBatdTtggFKqvE3xCSGE8JA7LfYcYDCQXkid\nBGB+3tfrgda+hSWEEMJbRSZ2rXW61vp0EdVigJS8r08B1Z0rKKWGKqWSlFJJJ06c8DxSIYQQbrHr\n5mkG4JgfW87qvFrrmVrr1lrr1nFxcTY9rRBCCGd2JfYtQPu8r1sCyTadVwghhIc8nnmqlOoCNNFa\nv5Pv8L+ApUqpDkAT4Aeb4hNCCOEht1vsWuuEvP9XOyV1tNYHgW7AJqCr1jrHfAYhhBCBYNtaMVrr\nw1weGRP0Ar1VlRBCBEqJXASsOLaqEkKIQAn7xG7VMi9sqypJ7EKIUBfWid1Vy9w5qTv4c6sqIUT4\nC5Yu3rBO7K5a5pFKkaO1qb4/t6oSQoS3YOriDevVHV21wHO0DvhWVUKI8FZYF2+ghXVid9UCj4+N\nZkr/5sTHRqPyfS/960IIb7lqSBZHF2/IdsW405c1skdDU5+6o2Ue6K2qhBDhrWZsNCkWSVwD7aau\nDmh/e0i22B19WSlpmWgu92Ul/pxSoF6/6+OlZS6ECIiRPRqaungdXOUof1Ha4iaiv7Vu3VonJSV5\n/fh2U1dbvjPGx0azaXQXX0ITQgivOXoSrPIT+J6jlFJbtNZFLoseki32YOrLEkIIh37Xx7NpdBeU\ni/JA5ajQS+y5uTz936VUPmdeIl6GKwohgoGrXBSoHBVaiT09He66i6eWzGDGon8QmXv5pmhUhOLc\nhYvUG72EdlNXB6wvSwghnFn1twdySHXoJPa9e6FNG0hMBODmg9uY+P3HKCA2OgoUpJ7LLvRmqhBC\nBEJxD9wIjZunFy9Cw4Zw4IC57NNPaXewutxMFUL4Vf4h1hWjo1AK0s5lB3TpgPC6eVqqFMycCREW\n4T7yCBX/t9PyYXIzVQhhB+ch1mmZ2QV6CEbM20rdIOoGDo3EDnDrrfDKK+bjmZnMSpxCxcwzpiK5\nmSqEsIPVcgH5Ofo9Cu0GXrYM0tL8E6CT0EnsAM8+C4MHmw7Hpx7h3cXTiMg1zzAVQghfefLp33J9\nmK++gj59jAbqyZM2R2cWWoldKZgzB5o3NxW1P/ATL/3nc5lhKoSwnaef/gu8ESxeDPfcAzk58NNP\n0KULHD9uc4QFhVZiB4iJgYULITbWVDRk3Wf82jqTTaO7SFIXQtimsOUCrFx6I1ixAu66C7KzLxdu\n3w4JCXDsmL1B5hN6iR3gmmvgs8+MFryzBx+EndY3U4UQwhvOwxdjo6OoVDYKwDTL9FI38Nq10K8f\nXLhgPmGtWlCxot/iDY3hjq5Mngxjx5qP168P//mPZateCCHsZLnSbNYh6NYNzp41PyAhAZYsgbJl\nPX4ud4c7hnZi1xoGDIAFC8xlt98OX39tPURSCCH8JSnJuEmanm4uu+UWWL4cypXz6tS2jmNXSs1R\nSn2vlBrnorySUmqpUipJKfW+p8F6TSn46CNo3NhctngxvPRSwEIRQgi2bYPu3a2TeuvWsHSp10nd\nE0UmdqVUfyBSa90WuFopVd+i2hDgk7x3kvJKqSLfUWxTvrxxM7VCBXPZyy8brXYhhMgn8ecU2k1d\nbe/aUrt2QdeukJpqLmvZ0mip+7FfPT93WuwJwPy8r1cA7S3qnASaKaVigVrAb84VlFJD81r0SSdO\nnPAyXBcaNoSPP7YuGzLEWGfGR365EIQQAefuRj0e2bfP6H754w9zWZMmsHIlVK7s/fk95E5ijwEc\nP/EpoLpFnY1AHeBJYHdevQK01jO11q211q3j4uK8DLcQffvC+PHm42fOkH5bHzhjnpnqLr9cCEKI\nYmH7ptO//mqMTT961FzWoAF89x34I+cVwp3EngE4RueXc/GY8cBftNYvA3uAh+wJz0MvvsjRDl1N\nhyv8uo/DdwyC3FyvThtMu48LIXxj60Y9v/1mJPXffzeX1atnJPUrr/T8vD5yJ7Fv4XL3S0sg2aJO\nJaC5UioSaMPlpRMCKyKCP3V+ggOVapqKaq75FqZO9eq0smOTEOHDtk0wjhwxknpysrmsVi1YvRqu\nusrzAG3gTmJPBIYopaYDg4CdSqmJTnWmADOB00Bl4DNbo/TA/85HMuzOsZyNusJcOG4cfPutx+cs\n7t1QhBD2sWUTjOPHjT71X34xl9WoYbTU69b1LVAfFJnYtdbpGDdQNwOdtdbbtNbjnOr8R2vdVGtd\nTmvdTWud4Z9wi1YzNpp9cXV4rtfT5kKtjTUb9u/36JzFvRuKEMJ3jgEQI+ZtpUypCCqVjfJubalT\np4zJR7t3m8vi4oykXt9q8GDguDWOXWudqrWer7W2uDsQXBxJeFmj9sy4eYC5Qloa3Hmn9YwwF4p7\nNxQhhG+s1lPPys7l9cHXeba21OnTxjj17dvNZZUrw6pV1vNqAiy0Z5664Jjie/RUBp8m/p02+yye\na/Bgy/VmLKcHSwIXIqS1m7ra913WzpyBHj3g++/NZRUrGi31Vq18jLRw7s48LeXXKIpJv+vjLyfj\n0e2NGV+//lqw0rx5xvHnnrt0yPGu7hgB4xjW6DinECI0+TwA4tw5Y5kSq6RerpyxiYafk7onwn8h\nlcqVjZmp0RY3OkeNMj465ZFhjUKEp8IGQBQ5+TAry1ilcf168wmio40Fvdq29UPU3gv/xA7GdN45\nc8zHc3Ph7rsvDVeSYY1ChCdXAyA6N4orfPLhhQvGQoMrV5pPWqYMLFoEHTv6/wfwUMlI7GCMhnnm\nGfPxkyeNm6nnzsmwRiHClKsBEGv2nHD5Kf3r/ySz7oZbjRa5s6goY1XZruYJkcEgLPvYXXrlFdi6\n1Zg4kN/WrTBsGCNHTGHMwv8W+EXLsEYhwkOBe295Rszbaln3yKkMePBBOu3eaC6MjDTu0fXq5Y8w\nbVFyWuwApUrB559D7drmsrlz6bdxgQxrFKIEsfo0rnQuryx7mzt2rzOV5agI+OQT41N+EAvL4Y5F\n2rIF2rWD8+cLHo+MNIYsdepUPHEJIQLKeSQcWjNpxbvct9U8Qz0XxcjeT/Pa4ukBjvIyWzfaCDut\nWsH7FvuB5OTAwIHGwj5CiLCXv+8drXnxu1mWSR1gbI/hbG5/e4Aj9E7JTOwAf/oTPP64+fiJE8au\n4llZgY9JCBFw/a6PZ9OozkzcPJeHtyyyrDPh1qEk3tg7ZO63ldzEDjB9OnToYD7+448wfLixtowQ\nIvy99BL3r59nWTQ54SFWdh0cUvfbSmYfe35Hj5LZ4jqiTxwzl733HvzlL4GPSQgROK+8AqNHWxbt\n/suzNH7v1QAH5Jr0sbsp8UgOD/UexflIi5GfTz4J//534IMSQgTGG2+4TOqMGUPjGdMCG49NSnxi\nn7Z8L5urN2B8V4uWeXa20d9++HDgAxNC+Nd778GIEdZlI0bApEmmRQJDRYlP7I7lAj6/rieftuxp\nrnD0KEk3daXTxOWyx6kQ4eLDD+Gvf7Uue+wxeO21kE3qIIm9wASFCV2H8VNN813v1im7+fNXb8oG\n1kKEg08/hUcesS57+GF4552QTuogib3A4kAXSkXxWL8xnIipZKp3/9Zl9Ela5vZKj0WuGCeECLyv\nvoIHHrAe8XbffTBzJkSEfloM/Z/AR86LA5WqVYvdb80hOyLSVPfvK2cQt8t6bYn8nHdrMa0YJ4QI\nvMWLjdVcc3LMZQMGwEcfGbPPw4AMd3ThtTue5NlFb5uOH6sYR/X//ReqVXP5WFt2axFC+MyxI9o1\nP29i9ld/p3ROtrlSnz7w5ZdQunTgA/RQid5ByQ7XjH+eBcl76L+94DrM1U+fgEGDjPWZo6IsHyvr\nugtRfBzJPCUtEwW0ObSdmQsmWif1Hj3giy9CIql7osR3xbjS74arKPX+e+yJb2AuXLcORo50+VhZ\n112I4pG/GxTght93MefLl7ni4gVz5c6djTXVy5QJcJT+51ZiV0rNUUp9r5QaV0S9GUqpPvaEVvz6\n3nwNjf69EqpWNRe++SbMnWv5OFe7tYTKOhNChKr821u2PLyXj74YT0y2xbpPt9xi7H5UtmyAIwyM\nIhO7Uqo/EKm1bgtcrZSq76JeB+BKrfU3NsdYvGrXhvnzrW+q/PnP8PPPpsOudmsJlXUmhAhVju7O\nJscO8H/zX6T8BXP3566rGsLSpcYm1GHKnT72BGB+3tcrgPbAvvwVlFJRwCxgqVLqDq3113YGWew6\nd4Zp08xb62VlGQvuJyWZWvVWu7UIIfyrZmw0Mft28/G8cVQ8f9ZUvqv61fw69yuaVKxYDNEFjjtd\nMTGAY5zeKaC6RZ0HgF3AP4CblFJPOFdQSg1VSiUppZJOnDjhbbw+8Wls+dNPw733mo8fPGgMobp4\n0b5AhRBemdAoik/m/Y0qmemmsl+r1SH504X07tS0GCILLHcSewbguOtXzsVjrgdmaq2PAnOBzs4V\ntNYztdattdat4+LivI3Xaz6PLVcKZs2Cli3NZd99By+8YGu8QggPHThAt8fvIe5sqrmsQQPqbdtM\nry4tAh9XMXAnsW/B6H4BaAkkW9T5Bbg67+vWwEGfI7NZ/psqDo7dyN1WtiwsXAiVzDNTmTbN6IsX\nQgTeoUPQpQukWDTU6tUzGl9XXhn4uIqJO4k9ERiilJoODAJ2KqUmOtWZA3RWSq0H/goEzwLGeWwb\nW16vnrEhttW044cegh07vIhOCOG1w4fh1luNblFntWrB6tVw1VWBj6sYFZnYtdbpGDdQNwOdtdbb\ntNbjnOqc0VoP1Fp31Fq31VoH3dx5W8eWd+8Okyebj587Z9xMTbX4KCiEsN/x40ZS/+UXc1mNGkZL\nvW7dgIdV3Nwax661TtVaz8/rQw9Jto8tf/55Y30JZ/v3G4sJWa1HIYSwz8mT0LUr7NljLouLM5J6\nfcvR2WGvxMw8tX1suVLw4YekX2PxxrBsGYwf71O8QohCpKUZn5ytuj4rV4ZVq6Bx48DHFSRkETAf\nJP6cwj9nf8v8OU9RwWLMLAsWGF0zQgj7nDljJPXNm81lFSsaLfVWrQIfVwDInqcBMG35XvaUv5Kn\n+jxHLhYL8z/wAOzeHfjAhAhXZ89C796WST27bAx8+23YJnVPSGL3gWNEzZprbuSN9haTlzIyjBb7\n6dMBjkyIMJSVBf36wYYNpqLMUmV4+K7xJJapVQyBBR9J7D7IP6Lm7VsGs/LaNuZKe/caLffc3ABG\nJkSYOX/e2Fh+1SpzUWQUj9z1NzbUbOLZvJQwJondB/lH2mgVwTO3P8P+yhbjZRctgonOQ/+FEG7J\nzjaW7Vi61FR0IaIUw+4cy7/rXgfIngcOkth9kH+kDUBGmRiG3jmWjNIWY+MnTIAlSwIboBChLieH\n3/sMhMREU1F2RCTD+41m7TWX7yXKngcGSew+6nd9PJtGdyE+NhoN7K9ai2d7jzBX1NoY375vn7lM\nCGGWm8uhfndz1XLzYrE5KoIRtz/Lyvo3Xzomex5cJondJvk/Ai5vcAtvtx1srnT6tHHz58yZAEYm\nRAjSGv7yF2ov/tJUlIviuV5Ps7hxx0vHZM+DgiSx28T5I+Dr7e9lzdUWw6527YKHHzYuXCGEmdbw\n1FPGaqoWXugxnIXNLm8K79gkXpL6ZZLYbeK8ZEFuRCSj7xxFxlV1zJW//BL+8Y8ARidEiNAaRo2C\nt9+2LH6x6zA+v67npe8d3S8+7bUQhiSx28RqyYIx991CuaXfWO+rOGYMLF8e8DiFCGoTJhhLYFuY\n2Plh/q9Vn0tTAR3dL4Bvey2EIVlSIBDmz4fBFn3ulSoZ2+pdfbW5TIiSZvJkGDvWsmhmt4eYcsNd\n1IyNZmSPhgW6XdpNXU2KxTBHRxdNOHF3SQF39jwVvho0yEjgzi2R1FRjZuq//w0xMcUTmxDB4PXX\nXSZ1XniBoZMmMdTFQ23bayGMSFdMoEyebCwx6mz7dvjzn92+mSp9iSLszJhh3ig+z6wb76RduS6F\nXue27rUQJiSxB0qpUvD555yrYTEz9bPP4I03Ln3rKnn7vG+rEMHmgw9g+HDLon/d0JtJnR8m5XRW\node57XsthAFJ7AGUeCiL+3uPIqtUaXPhyJGwZk2hyduWfVuFKGaOhsvTfZ4j99FHLet83qI7E7oO\nM/Y9oPDr3Pa9FsKA9LEH0LTle0mpUo/RPZ/gjcWvFSzMyYFBg/i/R94ikwoFihwXtfQlilDnaLgk\n7FjHa0teJ8KiC3Jh08680GM4WhVsdxZ2nfe7Pr5EJ3Jn0mIPIMeFmdi0Mx+06muu8McfTPjXi5TJ\nPm/5WOlLFKFu2vK93LL737z1zTQitcWKpwMH8vo9Y8iNiDQVyXXuPknsAZT/wpzc+WE212pmqtPi\n6C9MWjHDdDPVMcxL+hJFKLv2p43MSJxCVK7FnsB9+8Inn/BMryZynftIEnsA5U/MFyNL8fgdozhS\nvqqp3oD/fscDPy2+9L3jopa+RBHS1qxh5sJJlMm5aCr6vsGNxnyPqCi5zm0gE5S84LiR6egecZ4w\n4cljJ8Wfo8MjdxGZfaFAveyISO69exKHm9/o8vy+xCFEQG3cCD16wLlzpqLNdVpy/LMv6dv22mII\nLLS4O0HJrcSulJoDNAGWaK1d7hihlKoOfKu1vr6w84VyYnfc/Mk/OiU6KtKnFsXkASN54atXTcdP\nlqtElT07IN46qdsdhxB+8eOPcOutlquabqvTjEOfLqDPLfWLIbDQY9tm1kqp/kCk1rotcLVSqrDf\nwKtAWN/h8MeQw1nXJvDx9b1Mx6tkpBrbgZ0330yVoY8i2CX+nMKDT87kdIfO1ktV33QTLbdvkqTu\nB+70sScA8/O+XgG0t6qklOoCnAWOuigfqpRKUkolnThxwotQg4M/hhzWjI3m5Vv/TFJ8Y3PhDz/A\nE08EJA4h7JL4cwof/PMbps8eScXzZ80VrrsOvv0WKlQo8BiZVW0PdxJ7DOB4hU8B1Z0rKKVKA38D\nRrs6idZ6pta6tda6dVxcnDexBgVvhhwWdcGO7NGQUldcwWP9xnCsXGXzCWbNMq1NLUMfRTCbN3cV\ncz4ZQ+XMdHNh06awcqWxCF4emVVtL3cSewaXu1fKuXjMaGCG1jrNrsCCladDDt25YB2jAEpfFc9f\n7xhDdqTFvLHHH4fNm72OQ4iAOXCA6TOfJe6sOR3sr3wVfPcdVC04Gky6Fu3lTmLfwuXul5ZAskWd\nrsBwpdRa4Dql1GxbogtCng7FcveCdeyd+tXc54h6x2KTgQsXjP72o0e9ikOIgDh0CLp0oUbGSVPR\nwdgreWboq1Dd9KFfuhZtVuSoGKVUBWAD8B1wG3A3MFBrPc5F/bVa64TCzhnKo2I8VW/0EqxeYQX8\nOrW39YO0NlZ8nDPHXNa+vdHiKW2x3kweGQYprPj9ujh8GDp2hP37TUW/V4jj7ntf4feK1YjP99yO\nmKzWU4fwXFPdF7atx661TldKJQDdgH9orY8C2wqpn+BBnGGvZmy05UVbaF+4UvDOO8aSvj/+WLBs\n40Z49lmXW4c5D4N0dP0AktxLML9fF8eOGUMaLZL60XKVuf/uSfxesVqB5046eIqvtqSYPtE6SNei\n99yaeaq1TtVaz89L6sIDhfWFF3pT9Yor4KuvoFo180nfeQf+9S/L55O+SmHFr9fFyZPQrRvs2WMu\nq1aNEX9+jeRKNU3P/dkPv7lM6tK16BtZUsDPXPWFgxv7NNaqZUyzjjQviMSwYbBly6VvHW8Srj7S\nSl9lyea3Puy0NOjeHXbsMJdVqQLffcfm0taj4HJcdAMrYNPoLpLUfSDL9gaA1ZKi7aaudtmCKlC3\nUyeYPh2eeqrgSc+fh/79ISmJxN8vmGahOpNhkCWbV12CRTlzBnr2hJ9+MpfFxsKKFdCsGTVjj1s+\nd6RSlsldrlXfSYu9mHjUgnriCbj/fvPxQ4dg8GCmL91VaFKXvkph+/DYs2ehd29jAp2z8uWNyUc3\n3FDoc9/TppYM2fUTSezFxKMJRkrB++/D9RZL8KxZwwNfz3D5PNJXKcDm4bGZmXDHHbBhg7msbFlY\nsgTatCnyuSf2ay5Ddv1EVncsJl4t4nXwILRqZdyscvJkn5EsatKpwDEZKibs4hiW+Mcf6Xy4eCq3\n7LVoqV9xBSxebIyOEX5h2yJgwj+8akHVqQOffw4R5l/bK8veovHxA5e+l4+0wi6ORsixk2d4a9Er\n1km9dGlYuFCSepCQFnsomjYNnn/edDilUg16D5lOTI1qMilJ2Kbd1NUcPZXBm9+8yu17LLpfSpWC\nL780umeEX9k2QUkEoeeeM4Y6zptX4HB86hG27vkQpi+1HiIphBeOpJ5l2rI3rZN6RAR88okk9SAj\nXTGhSCljuYHmzc1lK1bAOMvVHoTwXG4ub6z5J3f9d7W5SCljotygQcUQmCiMJPZQFRNj9GnGxprL\npk41PhqLEs+nNc61hqeeou+PSy2Lx/R4nHa/15SldYOQJPZQds018OmnRgve2YMPws6dAQ9JBA+f\n1jjX2riP8847lsUvdh3GvJZxh3vsAAAVQ0lEQVQ9ZN30ICWJPdTddhtMtNiG9uxZuPNOY8q3KJF8\nWh/mxRfhVfM+vAATOz/M/7Xq4/k5RcBIYg8HY8YYSdzZvn3GjNXc3MDHJIqd1+vDTJpk3VgAXu0w\nhNk39Xd5TtneLjhIYg8HSsFHH0GjRuayJUvg5ZcDHpIofl5tn/jaa65vvo8dy8JeD7o8p2xvFzwk\nsQc5t1tAFSpAYqKxToezl16CRYv8G6gIOh6vD/Puu8ZQWivPPgt//3uh55Qlo4OHJPYg5nELqGFD\nmDvXuuz++2Gv/IGVJB7Nbp4929hX18rw4cakOKUKPadsbxc8ZOZpEHO1vnqRa8CMH2/d/dKokbEa\nX4UKNkYpQt7cufDAA8ZIGGePPmosQGexjIUzr69X4TZZKyYMeN0CGj8ebr/dfHzPHmMYZCE3U+Xm\nV+jz6Hf4xRfwpz9ZJvVDve+iQ71B1HthmVvXgu1LAwuvSWIPYl7d/AKjdfXxx1C/vrls4UJjApOF\nQN/8kjcR+3n0O/z6a7j3Xss3+t+79aFXy4f4Lf2C29eCrUsDC59IV0wQ82pp3/x27jTWxT57tsDh\nXBTPPTiZjk8OKXCeQH6U9vln8/I5py3fy+G0TGrGRoflQmlu/w6XLTPWd8nONp/kjjvoeONfOXTG\nXCbdKsVLumLCgM8toKZNjWGQTiLQTPhsIh++t6hACyyQN78CPYKipAzFc+t3uHq1sa2iVVLv2RPm\nzeM3i6Re2PlFcHFrdUel1BygCbBEa22auaCUqgh8DkQCZ4HBWusLdgZaUlntl+qRAQNg9GhT90uF\n82eZ9elY/hpbgX7X3wf4aV9MFwI9gqKwN5JwarUX+TvcuBH69IGsLPODu3SBBQugTJmAXgvCfkW2\n2JVS/YFIrXVb4GqllEXHLfcB07XW3YGjQE97wxQ+mTiR9XXN2+pVO5vKtNkj4fhxILA3v7y+f+Cl\nkjIUr9Df4Q8/QK9ecO6c+YHt2xtzHaKjiz6PCHrudMUkAPPzvl4BtHeuoLWeobVemfdtHHDcluiE\nPSIjmTzkRX6pfJWpqF7qEejWDY4cCejNLzsShyc3XwP9RlJcXP4O9TGjm+XMGfOD2rQxZijHxBR9\nnjD6dBPOirx5mtcN85bWeptSqjtwg9bacliFUqotMFFrbdofSyk1FBgKULt27VYHDx70OXhRNMcN\nw5S0TOLTj/PlxyOpkWHeM5U6dYwbao0bBzw2b25menrztThu1vrC1hu9O3ZA586We+Vyww3w3XfW\nyz+LoOPuzVN3EvubwGda68153TKNtNaTLepVxmjR36W1LjRry6iYwLBKZg1OHOSLT56n4vmz5gdU\nqmQMgevQIYBResebETyhMirG1jehPXugU6dL3W0FNG8Oa9ZAlSo+RiwCxc5RMVu43P3SEki2eLLS\nwBfAmKKSuggcqxuG/4urw6gHJ0PZsuYHpKYa3TIhsEmHN33m/a6PZ9PoLvw6tTebRncJyqQONo4Y\n2r/f2FzaKqk3bAgrV0pSD1PuJPZEYIhSajowCNiplHIeGfMIcAMwVim1Vik12OY4hRdcJbnlsdcY\nQ96qVjUXnj+PHjQI3njDz9H5Jpz7zG250XvwoDHK5fBhc9k11xjdL9WrexmhCHZFJnatdTrGDdTN\nQGet9Tat9TinOu9prStprRPy/s2zOpcIrEKTX5s28P33ZNSqaypXWsOIEfDMM0G7lns4j9rw+U0r\nJcVI6ocOmcvq1DHe1OOD89OKsIdbE5S01qla6/la66P+DkjYp8jkd+21DH7gNX6u4SIZvv463H23\n9ZjnYhbOozZ8etM6dszofjlwwFxWs6bRUq9d26ZIRbCSJQXCXFE3DOuNXkKZ7CzeXjSNbr/8YH2S\nDh2Mtd4rVw5Q1MKrG71//GGMfvnvf81l1avDunVG37rdzysCxrZRMf4giT14OEaXRObmMGHV+wz5\n2XpHeho3NoZD1qkT2ACFS/mTcMMyF/l8/jhi91gk9SpVYO1aaNasyPOF0pDQkkjWihFucXzsz4mI\n5G/dHuOVTn+yrrh7N7RtC1u3BjbAMOftCpf5174pe/4cU2c9b53UY2ON0S9FJHUI/Po9wn8ksZdw\nBfqqlWJRzwdI+vubEBVlrnzkiNEts2KFX2Ipacv4+rIwmSMJX5GdxZyvXua6I/8zVypfHpYvh+vN\ny0lYKSnLLpQEbi0CJsJP4X2pXaBtU2MFwPT0gg/MyIDevY2t1P7konXvZTz5uwEcSQ4Ii24Aq9fb\n3YXJrB57OC2TqJxs3kucws2/WbTUY2KMrrObbnI7Rln4K3xIi70EcquleOutsGGD9bC4ixeNnZgm\nTbLeTs0L4dwN4Or1tkqiULCF7Oqxla+I4PXF0+l8YIv5BFdcAd98A+3aeRRnOA8hLWmkxV4Cub2E\nbYsW8P33cNttxqYdzsaNM8ZKv/sulPLtUgq3boD8rewIpchxegPMzM4h0uI4FGwhW/6uLlxk0sp3\nuX3PBtNjc0tFEbFggTE6xkOO372Migl9kthLII+SaK1aLJkxn6oP3EObg9vN5TNnGhNi5s0rsDqg\np8KpG8C5W8kqeTuOR0dFmkah5G8hm34nWvPCmg/o//O3pvPpiAgiPv3EeCP2ks/r/4ugIF0xJZC7\nMxsdNzOHL/2VIQNeYlHjjtYnXLIEEhIKrEni6kaoq+Ph1A1g1cq24phUVdgkK+ffyfDv5zP0x4WW\n55ty5zPU21K2RNx4FoWTFnsJNLJHQ8vxyvmTqHOr80KpKJ7q8xyHK8Txlx++Mp80KckYDrlsGYln\nYyxvhCYdPMVXW1IKvUEaDt0A7nQfOV7volrI+X9XD2z5hpEbPrasN6XbUGZemwCE341n4TmZoFRC\nFTXD0NWyuAAPbPmGCatmEoHFtVOlCkMHTWBFhXqmIld9yuGyQXL+te+tRCpFrtZerT2/Y8rb/O2L\nVyzLZ9/6Jya2Hmg6Hi6vq7hMZp4Kn9QbvcQqbV/SZ/9m3vhmGpHnz5vKskqV5om+z7Oy/s1uPZcC\nfp3a27tAg4TVrM38fJrBmZho7F2bY3Hup5+mXulb0UqZisLhdRUFycxT4ZPCblrGx0Zz6wt/IXL1\nasv1Y664eIF/LpzM/T8tKXA80iL5FPVcgWDHxKjC+tWd+849er5Vq2DwYOuk/uCD8Npr1KxksbY+\ngXldS9qkslAhiV1YcnUz843B112aXFNvUSr3PDids/Hm1QIjdS4TV77HqLUfoXQu0VGR3NOmVtDd\nIPVl9md+rvrVFRTY1MOj5/v+e+jXDy5cMJfddRfMmgUREcV249mu107YTxK7sORqWVygwB/z91FV\n6TFwKqmNW1ie57EfvuT95W/yyu0NmNivedAttWvXxCh3Rxq5/Xzbt0OvXnDWYgvD7t3hk08uzR0o\nriWMw3lSWaiTUTHCJasRG+2mrjb9Mf9epgIDB09m1Q/vGtPYnXTf9h2MeRQWLAi6cdJ2TYxyZ6SR\nW8+XlWUs1/DSS5CWZqp3smVrBrV7kgPjVxW4CVscr2u4TSoLJ9JiFx5x9Ue7PxNYtAgefdT6gWvW\nGAuI/fab/4Lzgl1b7LnbanY+b+mL2TQ5doCHD2yAZ581tq174gljbXUnaQ2bclu3Uew/R1B0fYTz\n9oShTkbFCI8UNgwyNjoKhWbIqo95ZuMn1ieIjzda9c2b+zFK91mNZlEYiTPezrH0WsOhQ2xeuIbv\nv17LtUcP0PDEQa4+9TultBvbDzZoQO+Bk9l58QpTka/DGr3dXEPWbw88d0fFSFeM8IhVl4NDWmY2\nAG+1u4cj5asy5du3zUkrJQXat4eFC419Of2sqKSVf2JUSlrmpaQOPkz0SU+HHTuMf9u3G/927ID0\ndG4G3BsEmk+tWrByJbtm7LAs9qXrw5dVNcNpUlm4kcQuPOKcCF35okU3jpWrzD+/nkrZC0710tOh\nZ0/46CO4917Lx3vairSqD7hMWo6fwXkZXeefyXJxNIeLF2HfvoLJe/t2OHjQZZweu+sueOstqFmT\nmrG/2LaeTmGTqQr9mZ0E2z0TYZCuGOG1oiYxATQ7+guLl0+Foy72QZ86FZ5/HvKNcff0I76r+ldE\nRZB6LttUPzY6ivMXc031XY1DV1rz64jWlxO34/9du8BigpYtBgyAv/3NWGEzj11dH0VNpgKZ3BSs\npCtG+J2rFRnzS23UHCbkLf27Z4+5wujRxtK/b70FkcZYbLeXFc7jqr6rxOXoMnKuH6kUpS5kUf/k\nbzQ+/iuNTiTT8EQyTf84CP8wj1CxTXy8cc+hRQvjX/v2lnvL2tX14c4iZXIDNLS5ldiVUnOAJsAS\nrfVEb+uI8FJYfzvkG+5XNx42bYK+fY3/nc2YYfS9f/oplC3r8TA6b/qYlc7lqtPHaXz8VxqeSKbR\niWQanThI3dTDRLpzM9MbMTHG3qMtWhiJ3JHMLWbvumJH10dRr1dxTxoTvisysSul+gORWuu2SqkP\nlFL1tdb7PK0jwo9zC7JidBRKQdq5bHNrsnJlY3r8kCHw5Zfmk339tbFr0zffeLw2u6v6ji6XqDOn\nL7W+m/1xkEZ/JHPNsWTKOff920UpuPbaywnc0RKvVw8iin+EcWGftGwdCSSKTZF97Eqpt4BvtdZL\nlVJ3A9Fa6w+9qDMUGApQu3btVgftvMEkQkduLjzzDLz5pnV5/fqsePVDnvrxjMd97Bezsrj6VAoN\nTyTT/ORB+kScpMIveyh79LC/fhpSoyuwq1pd9laty+5qdUmucTUPPNKbPrdc67fn9JUMUwxddvax\nxwCOGRCngBu8qaO1ngnMBOPmqRvPK8JRRAS88YbRh/zMM+byffvo/uidzH75LZ5Pq2bdl6w1HD58\n6SZmvx076PzDFsoe2EdUzkX/xF26NDRpcrkF3rw5d6w7zbacsgVu/AIcXn8oqBO7DFMMf+4k9gzA\n8Rm4HNazVd2pI8RlI0YYNw2HDDEvcnXiBO0eu4dNw4YZszCPHIGkpfBhvrHhp04VeEhFO2OrXbtg\nF0rz5tCgAURFAfmGCubGGMNHnHg7rtzbiULekGGK4c2dxL4FaA9sBloCViv8uFNHlFAuE9agQXDl\nlXDHHZbrovD++8Y/fylfvkAL/NK/2NiCcW9NpmbsMcux8Va8HVfu7UQhIZy5k9gTgQ1KqZrAbcDd\nSqmJWutxhdTxeHKdCE9FJqyOHY2RMrfdZgx79IeICKPFnT+Bt2xpdAe5WCPeVdxXREUUmtS9HVHi\n6RBPIQpTZGLXWqcrpRKAbsA/tNZHgW1F1Dnth1hFCHIrYTVpAps3G7NQ16717QmrVSvYhdKiBTRu\nDNGetaI9HRsPvo0okZUShZ3cGseutU4F5vtaR5Q8biesGjXgu++MMe2jRsG5c4WeN6tUaf5XtTa/\nVKtH/a5taX5bByORV69+uQtlTyY1j6YxUp3yONl6mlB9XYjL0yGeQhRGZp4Kv/IoYUVEwOOPG90y\nzz0H69ZxrkxZ9pSqSEq5KvxaqSZ7qtVjT1xdDlaqQU6EMVM1PjaaTV2NpGpXX3VRY+OLWnfdU+6u\n5y6EOySxC7/yKmFdc42x+iPQrZBlgh3yt67t6qt2FfeEvk0vPY+do1dkCKKwkyR24Ve+Jix3ukTy\nt/7t6qsuKm5/JFwZgijsIold+J0vCauohcacW/929lVLohWhSiYSiaA2skdDoqMiCxxzDFC02n7O\nqr70VYuSRlrsIqh52pUjfdVCyEYbQggRMmSjDSFsFMh1XITwlSR2IYog67iIUCM3T4UoQmFj44UI\nRpLYhSiCrOMiQo0kdiGKUNiWfEIEI0nsQhRBxsaLUCM3T4UogoyNF6FGErsQbpDlBUQoka4YIYQI\nM5LYhRAizEhiF0KIMCOJXQghwowkdiGECDOS2IUQIsxIYhdCiDBTLOuxK6VOAAd9OEVV4A+bwrGT\nxOUZict9wRgTSFye8jWuOlrruKIqFUti95VSKsmdxeYDTeLyjMTlvmCMCSQuTwUqLumKEUKIMCOJ\nXQghwkyoJvaZxR2ACxKXZyQu9wVjTCBxeSogcYVkH7sQQgjXQrXFLoQQwgVJ7EIIEWaCNrErpaor\npTYUUSdKKfWNUmqTUuphV8dsjmuOUup7pdS4Quo8ppRam/dvq1LqfaVUKaXUoXzHmxdDXJYxKKVe\nUkr9qJR6txhiqqiUWqaUWqGUWqiUKu3P18rNmEx13HmcP+MK9OvkQVwBvabcjCngf3/5nrvQvBWo\nnBWUiV0pVQn4FxBTRNUngC1a63bAAKVUeRfH7IqrPxCptW4LXK2Uqm9VT2v9ntY6QWudAGwAZgEt\ngM8cx7XWOwIdl1UMSqlWQHvgJuC4UqprgGO6D5iute4OHAV6WsUZqJis6njws/gtLgL4OnkYV8Cu\nKXdjCvTfX77Y3MlbAclZQZnYgRxgMJBeRL0EYH7e1+uB1i6O2SX/uVdgXLwuKaXigepa6yTgZuB2\npdR/8locdu5e5W5cVjF0Ar7Sxl305UCHQMaktZ6htV6Z920ccNxFnIGKyaqOO4/za1wBfp3cjstF\nDP66ptyNCQjo35+DO3krgQDkrKBI7HkflRwfkdYCT2utT7vx0BggJe/rU0B1F8fsiusJD889HHgv\n7+sfga5a65uAKKBXMcRlFYMtr5evr5VSqi1QSWu92UWcdnDnZ/XrNeVDXEDAXidP4vLbNeVDTA5+\n+ftzRWud7kbeCsj1FRR7nmqth3n50AwgGjgNlMv73uqYLXEppd7MOzd553b5xqiUigA6A2PzDm3X\nWp/P+zoJ8PrjvA9xWcXgeL2Keqy/YkIpVRl4G7irkDjt4M7PalXHltfIx7gC+Tp5EpffrikfYvLr\n35+P/JqzHIKixe6DLVz+KNYSSHZxzJ/P50oH4Ad9eaLAx0qplkqpSKAfsK0Y4rKKwV+vl1vnVUqV\nBr4AxmitHQvD+eu1ciemQF9TbsUV4NfJ7bhcxBAMf4OB/PvzRGCuL6110P4D1ub7ugvwuFN5HWAn\n8CbGR61Iq2M2xlMB44KYDuwGKgJNgIkWdScD/fN93wzYDuwAJtn8OrkVl1UMGG/um/Jer71AvQDH\n9BiQCqzN+zfYX6+VRUwtLeKxitt0zM+/P6u4AvY6eRhXwK4pd2PKqxewvz+L516b93+x5ayQn3mq\nlKqJ8W63XOf1b1kds/H5KgHdgPVa66N2ntsXvsSllIoGegM/aa0PBENM/uJOTFZ1/P2zBONrBd7H\n5a9rypeYgkUgclbIJ3YhhBAFhXofuxBCCCeS2IUQIsxIYhdCiDAjiV0IIcKMJHYhhAgz/w/dCFVf\n6529egAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<matplotlib.figure.Figure at 0xef4ddd8>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "save()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This is reload\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey dense_2/bias not found in checkpoint\n\t [[Node: save_2/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_2/Const_0_0, save_2/RestoreV2/tensor_names, save_2/RestoreV2/shape_and_slices)]]\n\nCaused by op 'save_2/RestoreV2', defined at:\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 170, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n    app.launch_new_instance()\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n    app.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n    ioloop.IOLoop.instance().start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n    super(ZMQIOLoop, self).start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 827, in start\n    self._run_callback(callback)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 600, in _run_callback\n    ret = callback()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 258, in enter_eventloop\n    self.eventloop(self)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 164, in loop_tk\n    kernel.timer.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 161, in start\n    self.app.mainloop()\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1131, in mainloop\n    self.tk.mainloop(n)\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1549, in __call__\n    return self.func(*args)\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 596, in callit\n    func(*args)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 156, in on_timer\n    self.func()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 291, in do_one_iteration\n    stream.flush(zmq.POLLIN, 1)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 352, in flush\n    self._handle_recv()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n    callback(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n    user_expressions, allow_stdin)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n    shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2831, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-15-f3ce917be780>\", line 1, in <module>\n    reload() # 在jupyter下会报错，文件路径下操作正常\n  File \"<ipython-input-14-64f19b680ba1>\", line 12, in reload\n    saver = tf.train.Saver()  # define a saver for saving and restoring\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1281, in __init__\n    self.build()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1293, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1330, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 778, in _build_internal\n    restore_sequentially, reshape)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 397, in _AddRestoreOps\n    restore_sequentially)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 829, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\gen_io_ops.py\", line 1462, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 454, in new_func\n    return func(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3155, in create_op\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1717, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nNotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey dense_2/bias not found in checkpoint\n\t [[Node: save_2/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_2/Const_0_0, save_2/RestoreV2/tensor_names, save_2/RestoreV2/shape_and_slices)]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1277\u001b[0m     \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1278\u001b[1;33m       \u001b[1;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1279\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[1;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[0;32m   1262\u001b[0m       return self._call_tf_sessionrun(\n\u001b[1;32m-> 1263\u001b[1;33m           options, feed_dict, fetch_list, target_list, run_metadata)\n\u001b[0m\u001b[0;32m   1264\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[1;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[0;32m   1349\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_session\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfeed_dict\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1350\u001b[1;33m         run_metadata)\n\u001b[0m\u001b[0;32m   1351\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Key dense_2/bias not found in checkpoint\n\t [[Node: save_2/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_2/Const_0_0, save_2/RestoreV2/tensor_names, save_2/RestoreV2/shape_and_slices)]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\u001b[0m in \u001b[0;36mrestore\u001b[1;34m(self, sess, save_path)\u001b[0m\n\u001b[0;32m   1724\u001b[0m         sess.run(self.saver_def.restore_op_name,\n\u001b[1;32m-> 1725\u001b[1;33m                  {self.saver_def.filename_tensor_name: save_path})\n\u001b[0m\u001b[0;32m   1726\u001b[0m     \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mNotFoundError\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0merr\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m    876\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[1;32m--> 877\u001b[1;33m                          run_metadata_ptr)\n\u001b[0m\u001b[0;32m    878\u001b[0m       \u001b[1;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_run\u001b[1;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1099\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[1;32m-> 1100\u001b[1;33m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[0;32m   1101\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_run\u001b[1;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[0;32m   1271\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[1;32m-> 1272\u001b[1;33m                            run_metadata)\n\u001b[0m\u001b[0;32m   1273\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\client\\session.py\u001b[0m in \u001b[0;36m_do_call\u001b[1;34m(self, fn, *args)\u001b[0m\n\u001b[0;32m   1290\u001b[0m           \u001b[1;32mpass\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1291\u001b[1;33m       \u001b[1;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0me\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mop\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1292\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Key dense_2/bias not found in checkpoint\n\t [[Node: save_2/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_2/Const_0_0, save_2/RestoreV2/tensor_names, save_2/RestoreV2/shape_and_slices)]]\n\nCaused by op 'save_2/RestoreV2', defined at:\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 170, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n    app.launch_new_instance()\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n    app.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n    ioloop.IOLoop.instance().start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n    super(ZMQIOLoop, self).start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 827, in start\n    self._run_callback(callback)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 600, in _run_callback\n    ret = callback()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 258, in enter_eventloop\n    self.eventloop(self)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 164, in loop_tk\n    kernel.timer.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 161, in start\n    self.app.mainloop()\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1131, in mainloop\n    self.tk.mainloop(n)\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1549, in __call__\n    return self.func(*args)\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 596, in callit\n    func(*args)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 156, in on_timer\n    self.func()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 291, in do_one_iteration\n    stream.flush(zmq.POLLIN, 1)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 352, in flush\n    self._handle_recv()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n    callback(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n    user_expressions, allow_stdin)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n    shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2831, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-15-f3ce917be780>\", line 1, in <module>\n    reload() # 在jupyter下会报错，文件路径下操作正常\n  File \"<ipython-input-14-64f19b680ba1>\", line 12, in reload\n    saver = tf.train.Saver()  # define a saver for saving and restoring\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1281, in __init__\n    self.build()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1293, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1330, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 778, in _build_internal\n    restore_sequentially, reshape)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 397, in _AddRestoreOps\n    restore_sequentially)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 829, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\gen_io_ops.py\", line 1462, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 454, in new_func\n    return func(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3155, in create_op\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1717, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nNotFoundError (see above for traceback): Key dense_2/bias not found in checkpoint\n\t [[Node: save_2/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_2/Const_0_0, save_2/RestoreV2/tensor_names, save_2/RestoreV2/shape_and_slices)]]\n",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\u001b[0m in \u001b[0;36mrestore\u001b[1;34m(self, sess, save_path)\u001b[0m\n\u001b[0;32m   1736\u001b[0m         object_graph_string = reader.get_tensor(\n\u001b[1;32m-> 1737\u001b[1;33m             checkpointable.OBJECT_GRAPH_PROTO_KEY)\n\u001b[0m\u001b[0;32m   1738\u001b[0m       \u001b[1;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mNotFoundError\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36mget_tensor\u001b[1;34m(self, tensor_str)\u001b[0m\n\u001b[0;32m    350\u001b[0m         return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str),\n\u001b[1;32m--> 351\u001b[1;33m                                           status)\n\u001b[0m\u001b[0;32m    352\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\errors_impl.py\u001b[0m in \u001b[0;36m__exit__\u001b[1;34m(self, type_arg, value_arg, traceback_arg)\u001b[0m\n\u001b[0;32m    518\u001b[0m             \u001b[0mcompat\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mas_text\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mc_api\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTF_Message\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstatus\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 519\u001b[1;33m             c_api.TF_GetCode(self.status.status))\n\u001b[0m\u001b[0;32m    520\u001b[0m     \u001b[1;31m# Delete the underlying status object from memory otherwise it stays alive\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-15-f3ce917be780>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mreload\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;31m# 在jupyter下会报错，文件路径下操作正常\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m<ipython-input-14-64f19b680ba1>\u001b[0m in \u001b[0;36mreload\u001b[1;34m()\u001b[0m\n\u001b[0;32m     11\u001b[0m     \u001b[1;31m# don't need to initialize variables, just restoring trained variables\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     12\u001b[0m     \u001b[0msaver\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mSaver\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m  \u001b[1;31m# define a saver for saving and restoring\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 13\u001b[1;33m     \u001b[0msaver\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrestore\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msess\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'./params'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     14\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     15\u001b[0m     \u001b[1;31m# plotting\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\u001b[0m in \u001b[0;36mrestore\u001b[1;34m(self, sess, save_path)\u001b[0m\n\u001b[0;32m   1741\u001b[0m         \u001b[1;31m# a helpful message (b/110263146)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1742\u001b[0m         raise _wrap_restore_error_with_msg(\n\u001b[1;32m-> 1743\u001b[1;33m             err, \"a Variable name or other graph key that is missing\")\n\u001b[0m\u001b[0;32m   1744\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1745\u001b[0m       \u001b[1;31m# This is an object-based checkpoint. We'll print a warning and then do\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNotFoundError\u001b[0m: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey dense_2/bias not found in checkpoint\n\t [[Node: save_2/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_2/Const_0_0, save_2/RestoreV2/tensor_names, save_2/RestoreV2/shape_and_slices)]]\n\nCaused by op 'save_2/RestoreV2', defined at:\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 170, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\__main__.py\", line 3, in <module>\n    app.launch_new_instance()\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 596, in launch_instance\n    app.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 442, in start\n    ioloop.IOLoop.instance().start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 162, in start\n    super(ZMQIOLoop, self).start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 827, in start\n    self._run_callback(callback)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 600, in _run_callback\n    ret = callback()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 258, in enter_eventloop\n    self.eventloop(self)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 164, in loop_tk\n    kernel.timer.start()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 161, in start\n    self.app.mainloop()\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1131, in mainloop\n    self.tk.mainloop(n)\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1549, in __call__\n    return self.func(*args)\n  File \"C:\\Anaconda3\\lib\\tkinter\\__init__.py\", line 596, in callit\n    func(*args)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\eventloops.py\", line 156, in on_timer\n    self.func()\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 291, in do_one_iteration\n    stream.flush(zmq.POLLIN, 1)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 352, in flush\n    self._handle_recv()\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n    callback(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tornado\\stack_context.py\", line 275, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 276, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 228, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 391, in execute_request\n    user_expressions, allow_stdin)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 199, in do_execute\n    shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2723, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2831, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2885, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-15-f3ce917be780>\", line 1, in <module>\n    reload() # 在jupyter下会报错，文件路径下操作正常\n  File \"<ipython-input-14-64f19b680ba1>\", line 12, in reload\n    saver = tf.train.Saver()  # define a saver for saving and restoring\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1281, in __init__\n    self.build()\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1293, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 1330, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 778, in _build_internal\n    restore_sequentially, reshape)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 397, in _AddRestoreOps\n    restore_sequentially)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\training\\saver.py\", line 829, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\ops\\gen_io_ops.py\", line 1462, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py\", line 454, in new_func\n    return func(*args, **kwargs)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3155, in create_op\n    op_def=op_def)\n  File \"C:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1717, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nNotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:\n\nKey dense_2/bias not found in checkpoint\n\t [[Node: save_2/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_2/Const_0_0, save_2/RestoreV2/tensor_names, save_2/RestoreV2/shape_and_slices)]]\n"
     ]
    }
   ],
   "source": [
    "reload() # 在jupyter下会报错，文件路径下操作正常"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python [Anaconda3]",
   "language": "python",
   "name": "Python [Anaconda3]"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  },
  "toc": {
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": "block",
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
